### ISSUE TITLE
[Bug]: Search does not seem to be working correctly in 2.8

### ISSUE THREAD

**Issue by ktalley-vtech** [massCodeIO/massCode#117]
### Describe the bug

Search results are not returning correct/consistent results.  Here is one example:
![image](https://user-images.githubusercontent.com/54152105/178054974-63608653-cd90-4fb0-9cf9-582385586b94.png)

Also, other search scenario shows correct results for a split-second, but then returns to full/all snippets, which is obviously not correct.

### To reproduce

After installing 2.8, I tried to search for a specific text ("Splunk") in a snippet name.  The results briefly flashed with the correct results (there are 2), but then immediately returned to a result of all snippets.  I closed it down, restarted, and tried it again.  This time I get 1 correct result at top of list, and then all other (non-search-correct) snippets appear below it (this is example in the screenshot found in the description above).  This all worked fine in 2.6.1.

### Version

2.8

### OS

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment]
Closed because it was fixed in [v2.8.1](https://github.com/massCodeIO/massCode/releases/tag/v2.8.1)

**Comment by aderchox** [comment]
@antonreshetov I guess this is not quite fixed. I'm on 3.11.0 and I still get search results that do not actually contain the keyword I've searched for. I believe the fuzzy search it does is "too fuzzy". My understanding of it is, it's probably searching all the letters in the search keyword one by one, and then sees if it can find them all to connect them together, and then construct the search keyword? Which is an odd way of searching keywords? To verify this, one can just check the result and then find nothing highlighted.
All that being said, I wish there was an option in the settings for configuring the search to behave as an "exact search", or at least as a less-meticulous fuzzy search.
